### ISSUE TITLE
Write code for model CLASS

### ISSUE THREAD

**Issue by FarmHJ** [SABS-R3-Epidemiology/pkmodelling-g3#2]
- [x] Set up variables
- [x] Add peripheral components
- [x] Set up test
- [x] Write documentation with docstrings

**Comment by I-Bouros** [comment]
Should also include setting up a test for the class; It's ideal to be done at the same time.

**Comment by I-Bouros** [comment]
And add the documentation.

**Comment by I-Bouros** [comment]
Need to hear from Martin about how thorough we need to be with the tests.
