### ISSUE TITLE
Set up for solution CLASS

### ISSUE THREAD

**Issue by FarmHJ** [SABS-R3-Epidemiology/pkmodelling-g3#4]
- [x] combine model and protocol CLASS
- [x] solve the ODE
- [x] write documentation with docstrings

**Comment by I-Bouros** [comment]
Probably add a test was well

**Comment by I-Bouros** [comment]
... And add up documentation as you write

**Comment by I-Bouros** [comment]
Idea: do exactly what you did, but so to not repeat code for the two types of dosing (intravenous and subcutaneous), use the two methods that the protocol class should have a dosing_function and subcutaneous_comp_function, to create that ODE equation for q0 that we need to append for the intravenous case and add a q0=0 to the IC in that case. #11
